---

- hosts: all
  become: true
  tasks:
  - name: update packet
    apt:
      update_cache: yes
  - name: install web-server-apache
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu" 
  - name: php for apache
    apt:
      name: libapache2-mod-php
      state: latest
  - name: php
    apt:
      name: php
      state: latest 
  - name: database mysql
    apt:
      name: mysql-server
      state: latest