---

- hosts: all
  become: true
  tasks:
  - name: update packet
    apt:
      update_cache: yes
  - name: install web-server-apache
    apt:
      name:
        - apache2
        - libapache2-mod-php
        - php
        - mysql-server
      state: latest
    when: ansible_distribution == "Ubuntu" 
  - name: copy folder web
    copy:
      src: /var/www/html/
      dest: /var/www/html/
      mode: 755
      remote_src: true