  - name: create user with root groub
    tags: user
    user:
      name: enryu
      group: root
  - name: adding key in client
    tags: user
    ansible.posix.authorized_key:
      user: enryu
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKQ0fTLlciCjkERK13afhGBVyp3jQYQgdbmt7+JeXo1Z ansible"
  - name: add sudoers
    tags: user
    ansible.builtin.copy:
      src: sudoer_enryu
      dest: /etc/sudoers.d/enryu
      owner: root
      group: root
      mode: 0440
